### ISSUE TITLE
restart --tail causes a panic in 1.8.16

### ISSUE THREAD

**Issue by houmam** [yext/edward#170]
I updated to 1.8.16 this morning and when I restart a service with the --tail flag Edward panics

```
edward restart --tail servicename
servicename > Stop:  [OK] (272.381ms)
servicename > Build:  [OK] (532.519ms)
servicename > Start:  [OK] (569.047ms)
Edward> 2018/11/13 10:49:18.534165 runner.go:264: Service starting

-- Some Initial Logs --

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x1452fe9]

goroutine 22 [running]:
github.com/yext/edward/vendor/github.com/theothertomelliott/uilive.(*bypass).Write(0xc4203cc230, 0xc4200281c0, 0x18, 0x40, 0x0, 0x0, 0x0)
	/Users/username/go/src/github.com/yext/edward/vendor/github.com/theothertomelliott/uilive/writer.go:137 +0x49
fmt.Fprintf(0x16d5560, 0xc4203cc230, 0xc4201ace40, 0x5, 0xc42045b900, 0x1, 0x1, 0x15, 0x10cbc77, 0xc420122000)
	/usr/local/Cellar/go@1.10/1.10.4/libexec/src/fmt/print.go:189 +0xa5
github.com/yext/edward/output.(*CompletionRenderer).doRenderWithPrefix(0xc42045be50, 0xc4204465e0, 0x15, 0x15, 0x16d5560, 0xc4203cc230, 0x16dece0, 0xc4201e6fc0, 0x0, 0x0)
	/Users/username/go/src/github.com/yext/edward/output/rendering_completion.go:63 +0x50f
github.com/yext/edward/output.(*CompletionRenderer).doRenderWithPrefix(0xc42045be50, 0xc4203b63c0, 0xd, 0x15, 0x16d5560, 0xc4203cc230, 0x16dece0, 0xc42047a000, 0x0, 0x0)
	/Users/username/go/src/github.com/yext/edward/output/rendering_completion.go:53 +0x21d
github.com/yext/edward/output.(*CompletionRenderer).doRenderWithPrefix(0xc42045be50, 0x0, 0x0, 0x15, 0x16d5560, 0xc4203cc230, 0x16dece0, 0xc4203adbc0, 0x0, 0x0)
	/Users/username/go/src/github.com/yext/edward/output/rendering_completion.go:53 +0x21d
github.com/yext/edward/output.(*CompletionRenderer).Render(0xc4204db650, 0x16d5560, 0xc4203cc230, 0x1041965, 0x1013727)
	/Users/username/go/src/github.com/yext/edward/output/rendering_completion.go:30 +0x8f
github.com/yext/edward/output.(*Follower).Handle(0xc4202a55e0, 0x16dece0, 0xc4201e6fc0)
	/Users/username/go/src/github.com/yext/edward/output/tasks.go:41 +0x298
github.com/yext/edward/edward.(TaskFollower).Handle-fm(0x16dece0, 0xc4201e6fc0)
	/Users/username/go/src/github.com/yext/edward/edward/client.go:120 +0x43
github.com/yext/edward/tracker.(*task).handleUpdate(0xc4201e6fc0, 0x16dece0, 0xc4201e6fc0)
	/Users/username/go/src/github.com/yext/edward/tracker/task.go:232 +0x9c
github.com/yext/edward/tracker.(*task).AddOutput(0xc4201e6fc0, 0xc4203d2830, 0x1, 0x1)
	/Users/username/go/src/github.com/yext/edward/tracker/task.go:183 +0x68
github.com/yext/edward/instance.(*Instance).StartAsync.func1(0xc4202c8900, 0x16dece0, 0xc4201e6fc0)
	/Users/username/go/src/github.com/yext/edward/instance/start.go:80 +0x98
created by github.com/yext/edward/instance.(*Instance).StartAsync
	/Users/username/go/src/github.com/yext/edward/instance/start.go:77 +0x6b2
```

The service restarts and is still running as expected and when I use the log/tail commands directly it outputs the logs correctly.

**Comment by theothertomelliott** [comment]
Thanks for the heads up! Fixed for version 1.8.17.
